# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField()),
                ('amigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amigo', to='egresado.Egresado')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='egresado.Egresado')),
            ],
        ),
    ]
