# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-30 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='interes',
            field=models.ManyToManyField(blank=True, to='egresado.Interes'),
        ),
    ]
