# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-28 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egresado.Carrera'),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egresado.Sexo'),
        ),
    ]
