# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-21 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresado', '0002_amigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigos',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
    ]
