# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-22 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresado', '0003_auto_20171121_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigos',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='amigos',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
