# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-22 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresado', '0005_auto_20171121_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='apellidos',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
