# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-23 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresado', '0006_auto_20171121_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='nombre',
        ),
    ]
