# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-05 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresado', '0009_auto_20171123_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_corta', models.TextField()),
                ('descripcion', models.TextField()),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='medias')),
                ('interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egresado.Interes')),
            ],
        ),
    ]
