# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-06 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='multimedia',
        ),
    ]
